### ISSUE TITLE
Defults to Days since last PB when restarting livesplit

### ISSUE THREAD

**Issue by izzyhope58** [Minibeast/LiveSplit.SinceLastPB#1]
Whenever I restart Livesplit or load a layout, it is set to "Days since last PB" even if I save the layout as Attempts since or Both.

Love the component btw. Really cool feature that I'll be using in my runs from now on :)

**Comment by Minibeast** [comment]
I'm a little disappointed that I never noticed that until now. I see the issue, I will release a fix for it in a few hours.
